//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookLove.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supple
    {
        public int id { get; set; }
        public int idProvider { get; set; }
        public int idBook { get; set; }
        public int idClient { get; set; }
        public System.DateTime dateSupple { get; set; }
        public string description { get; set; }
        public double totalPrice { get; set; }
        public int count { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Client Client { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
