//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Confectionery.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataEmploye
    {
        public int id { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public int idLogin { get; set; }
        public Nullable<int> numberCertificate { get; set; }
        public System.DateTime dateRegistration { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
