//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewerlyStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Check()
        {
            this.Basket1 = new HashSet<Basket>();
        }
    
        public int ID { get; set; }
        public int IDClient { get; set; }
        public int IDJewelry { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Commission { get; set; }
        public double TotalPrice { get; set; }
        public int Count { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Jewelry Jewelry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basket> Basket1 { get; set; }
    }
}
