//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewerlyStore.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jewelry
    {
        public int ID { get; set; }
        public byte[] JewImg { get; set; }
        public string JewName { get; set; }
        public int CategoryID { get; set; }
        public string Material { get; set; }
        public long Pice { get; set; }
        public int ParametersID { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Parameters Parameters { get; set; }
    }
}
