//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewerlyStore.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JewelryStoreEntities : DbContext
    {
        public JewelryStoreEntities()
            : base("name=JewelryStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Check> Check { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Jewelry> Jewelry { get; set; }
        public virtual DbSet<Parameters> Parameters { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<SignIn> SignIn { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
